#
# Environment specific definitions
#

# our title
DASHBOARD_TITLE: 'Development Dashboard'

# the libra endpoint
LIBRA:
 title: 'Libra'
 url: 'http://docker1.lib.virginia.edu:8040'
 id: 'libra'
 time: 'libra-time'

# the registration endpoint
DEPOSITREG:
 title: 'Registration'
 url: 'http://docker1.lib.virginia.edu:8221'
 id: 'depositreg'
 time: 'depositreg-time'

# the deposit authorization service endpoint
DEPOSIT_AUTH_SERVICE:
 title: 'Deposit Auth Service'
 url: 'http://docker1.lib.virginia.edu:8230/healthcheck'
 id: 'deposit-auth-service'

# the deposit registration service endpoint
DEPOSIT_REG_SERVICE:
 title: 'Deposit Registration Service'
 url: 'http://docker1.lib.virginia.edu:8220/healthcheck'
 id: 'deposit-reg-service'

# the entity ID service endpoint
ENTITY_ID_SERVICE:
 title: 'Entity Id Service'
 url: 'http://docker1.lib.virginia.edu:8210/healthcheck'
 id: 'entity-id-service'

# the token authorization service endpoint
TOKEN_AUTH_SERVICE:
 title: 'Token Auth Service'
 url: 'http://docker1.lib.virginia.edu:8200/healthcheck'
 id: 'token-auth-service'

# the user service endpoint
USER_INFO_SERVICE:
 title: 'User Info Service'
 url: 'http://docker1.lib.virginia.edu:8010/healthcheck'
 id: 'user-info-service'

# SOLR service endpoint
SOLR:
 title: 'SOLR'
 url: 'http://docker1.lib.virginia.edu:8041/solr'
 id: 'solr-service'

# Fedora service endpoint
FEDORA:
 title: 'Fedora'
 url: 'http://docker1.lib.virginia.edu:8041/fedora/rest'
 id: 'fedora-service'

# redis service endpoint
REDIS:
 title: 'Redis'
 url: 'docker1.lib.virginia.edu:8379'
 id: 'redis-service'
