#
# Environment specific definitions (development mode)
#

# our title
DASHBOARD_TITLE: 'Libra2 Development Status Dashboard'

# the libra endpoint(s)
LIBRA:
 title: 'Libra'
 #url: 'http://docker1.lib.virginia.edu:8040'
 url: <%= ENV['LIBRA2_WEBAPP'] %>
 id: 'libra'
 time: 'libra-time'

# the registration endpoint(s)
DEPOSITREG:
 title: 'Registration'
 #url: 'http://docker1.lib.virginia.edu:8221'
 url: <%= ENV['OPTREG_WEBAPP'] %>
 id: 'depositreg'
 time: 'depositreg-time'

# the deposit authorization service endpoint(s)
DEPOSIT_AUTH_SERVICE:
 title: 'Deposit Auth Service'
 #url: 'http://docker1.lib.virginia.edu:8230/healthcheck'
 url: <%= "#{ENV['DEPOSITAUTH_URL']}/healthcheck" %>
 id: 'deposit-auth-service'

# the deposit registration service endpoint(s)
DEPOSIT_REG_SERVICE:
 title: 'Deposit Registration Service'
 #url: 'http://docker1.lib.virginia.edu:8220/healthcheck'
 url: <%= "#{ENV['DEPOSITREG_URL']}/healthcheck" %>
 id: 'deposit-reg-service'

# the entity ID service endpoint(s)
ENTITY_ID_SERVICE:
 title: 'Entity Id Service'
 url: 'http://docker1.lib.virginia.edu:8210/healthcheck'
 #url: <%= "#{ENV['ENTITYID_URL']}/healthcheck" %>
 id: 'entity-id-service'

# the token authorization service endpoint(s)
TOKEN_AUTH_SERVICE:
 title: 'Token Auth Service'
 #url: 'http://docker1.lib.virginia.edu:8200/healthcheck'
 url: <%= "#{ENV['TOKENAUTH_URL']}/healthcheck" %>
 id: 'token-auth-service'

# the user service endpoint(s)
USER_INFO_SERVICE:
 title: 'User Info Service'
 #url: 'http://docker1.lib.virginia.edu:8010/healthcheck'
 url: <%= "#{ENV['USERINFO_URL']}/healthcheck" %>
 id: 'user-info-service'

# SOLR service endpoint(s)
SOLR:
 title: 'SOLR'
 #url: 'http://docker1.lib.virginia.edu:8041/solr'
 url: <%= ENV['SOLR_URL'] %>
 id: 'solr-service'

# Fedora service endpoint(s)
FEDORA:
 title: 'Fedora'
 #url: 'http://docker1.lib.virginia.edu:8041/fedora/rest'
 url: <%= ENV['FEDORA_URL'] %>
 id: 'fedora-service'

# redis service endpoint(s)
REDIS:
 title: 'Redis'
 #url: 'docker1.lib.virginia.edu:8379'
 url: <%= "#{ENV['REDIS_HOST']}:#{ENV['REDIS_PORT']}" %>
 id: 'redis-service'
