#
# Environment specific definitions
#

# the libra endpoint(s)
LIBRA:
 title: 'Libra'
 url: <%= "#{ENV['LIBRA2_WEBAPP']}/healthcheck" %>
 time: 'libra-time'

ADMIN:
 title: 'Admin'
 url: <%= "#{ENV['ADMIN_WEBAPP']}/healthcheck" %>
 time: 'admin-time'

# the registration endpoint(s)
DEPOSITREG:
 title: 'Registration'
 url: <%= "#{ENV['OPTREG_WEBAPP']}/healthcheck" %>
 time: 'depositreg-time'

# the deposit authorization service endpoint(s)
DEPOSIT_AUTH_SERVICE:
 title: 'Deposit Auth Service'
 url: <%= "#{ENV['DEPOSITAUTH_URL']}/healthcheck" %>
 id: 'deposit-auth-service'

# the deposit registration service endpoint(s)
DEPOSIT_REG_SERVICE:
 title: 'Deposit Registration Service'
 url: <%= "#{ENV['DEPOSITREG_URL']}/healthcheck" %>
 id: 'deposit-reg-service'

# the entity ID service endpoint(s)
ENTITY_ID_SERVICE:
 title: 'Entity Id Service'
 url: <%= "#{ENV['ENTITYID_URL']}/healthcheck" %>
 id: 'entity-id-service'

# the token authorization service endpoint(s)
TOKEN_AUTH_SERVICE:
 title: 'Token Auth Service'
 url: <%= "#{ENV['TOKENAUTH_URL']}/healthcheck" %>
 id: 'token-auth-service'

# the user service endpoint(s)
USER_INFO_SERVICE:
 title: 'User Info Service'
 url: <%= "#{ENV['USERINFO_URL']}/healthcheck" %>
 id: 'user-info-service'

# SOLR service endpoint(s)
SOLR:
 title: 'SOLR'
 url: <%= ENV['SOLR_URL'] %>
 id: 'solr-service'

# Fedora service endpoint(s)
FEDORA:
 title: 'Fedora'
 url: <%= ENV['FEDORA_URL'] %>
 id: 'fedora-service'

# redis service endpoint(s)
REDIS:
 title: 'Redis'
 url: <%= ENV['REDIS_HOST'] && ENV['REDIS_PORT'] ? "#{ENV['REDIS_HOST']}:#{ENV['REDIS_PORT']}" : '' %>
 id: 'redis-service'
