#
# Environment specific definitions
#

# the libra ETD endpoint(s)
LIBRA_ETD:
 title: 'Libra ETD'
 url: <%= "#{ENV['LIBRA_ETD_WEBAPP']}/healthcheck" %>
 time: 'libra-etd-time'

# libra ETD admin endpoint(s)
ADMIN:
 title: 'ETD Admin'
 url: <%= "#{ENV['ADMIN_WEBAPP']}/healthcheck" %>
 time: 'admin-time'

# the registration endpoint(s)
DEPOSITREG:
 title: 'Registration'
 url: <%= "#{ENV['OPTREG_WEBAPP']}/healthcheck" %>
 time: 'depositreg-time'

# the libra OC endpoint(s)
LIBRA_OC:
 title: 'Libra OC'
 url: <%= "#{ENV['LIBRA_OC_WEBAPP']}/healthcheck" %>
 time: 'libra-oc-time'

# the deposit authorization service endpoint(s)
DEPOSIT_AUTH_SERVICE:
 title: 'Deposit Auth Service'
 url: <%= "#{ENV['DEPOSITAUTH_URL']}/healthcheck" %>
 id: 'deposit-auth-service'

# the deposit registration service endpoint(s)
DEPOSIT_REG_SERVICE:
 title: 'Deposit Registration Service'
 url: <%= "#{ENV['DEPOSITREG_URL']}/healthcheck" %>
 id: 'deposit-reg-service'

# the entity ID service endpoint(s)
ENTITY_ID_SERVICE:
 title: 'Entity Id Service'
 url: <%= "#{ENV['ENTITYID_URL']}/healthcheck" %>
 id: 'entity-id-service'

# the ORCID access service endpoint(s)
ORCID_ACCESS_SERVICE:
 title: 'ORCID Access Service'
 url: <%= "#{ENV['ORCIDACCESS_URL']}/healthcheck" %>
 id: 'orcid-access-service'

# the token authorization service endpoint(s)
TOKEN_AUTH_SERVICE:
 title: 'Token Auth Service'
 url: <%= "#{ENV['TOKENAUTH_URL']}/healthcheck" %>
 id: 'token-auth-service'

# the user service endpoint(s)
USER_INFO_SERVICE:
 title: 'User Info Service'
 url: <%= "#{ENV['USERINFO_URL']}/healthcheck" %>
 id: 'user-info-service'

# SOLR service endpoint(s)
SOLR:
 title: 'SOLR'
 url: <%= "#{ENV['SOLR_URL']}/#/" %>
 id: 'solr-service'

# Fedora service endpoint(s)
FEDORA:
 title: 'Fedora'
 url: <%= ENV['FEDORA_USER'] && ENV['FEDORA_PASSWD'] && ENV['FEDORA_URL'] ? "http://#{ENV['FEDORA_USER']}:#{ENV['FEDORA_PASSWD']}@#{ENV['FEDORA_URL'].gsub( "http://", "" )}" : '' %>
 id: 'fedora-service'

# redis service endpoint(s)
REDIS:
 title: 'Redis'
 url: <%= ENV['REDIS_PASSWD'] && ENV['REDIS_HOST'] && ENV['REDIS_PORT'] && ENV['REDIS_DB'] ? "redis://:#{ENV['REDIS_PASSWD']}@#{ENV['REDIS_HOST']}:#{ENV['REDIS_PORT']}/#{ENV['REDIS_DB']}" : '' %>
 id: 'redis-service'
